import { StyleSheet } from "react-native";
import { moderateScale, moderateVerticalScale, scale } from "react-native-size-matters";
export const style = StyleSheet.create({
  container: {
    backgroundColor: "#2E2E2E",
    flex: 1,
  },
  cards: {
    height: moderateVerticalScale(647),
    width: moderateVerticalScale(328),
    borderRadius: 16,
    marginTop:moderateScale(57),
    paddingHorizontal: moderateScale(24),
    marginLeft: moderateScale(33),
    alignItems: "center",
  borderRadius: moderateScale(16),
    backgroundColor: "#4C4C4C",
    marginRight: 8,
  },
  cards2: {
    height:moderateVerticalScale(647),
    width:moderateVerticalScale(328),
    borderRadius:moderateScale(16),
    flex: 1,
    marginTop:moderateScale(57),
    paddingHorizontal:moderateScale(24),
    alignItems: "center",
    borderRadius: moderateScale(16),
    backgroundColor: "#4C4C4C",
  },
  imgward: {
    width: moderateVerticalScale(245),
    height:moderateVerticalScale(267),
    marginTop: moderateScale(100),
    marginRight:moderateScale(30),
    marginLeft:moderateScale(31),
  },
  hendtext1: {
    height: moderateVerticalScale(40),
    // width: moderateVerticalScale(280),
    color: "#FFFFFF",
    fontFamily: "SF Pro Text",
    fontSize:moderateScale(22),
    fontWeight: 500,
    letterSpacing: 0,
    lineHeight: 32,
    textAlign: "center",
    marginTop:moderateScale(90),
  },
  donectext2: {
    height:moderateVerticalScale(40),
    // width:moderateVerticalScale(280),
    color: "#999999",
    fontFamily: "SF Pro Text",
    fontSize: moderateScale(13),
    letterSpacing: 0,
    lineheight: 22,
    textalign: "center",
    marginTop: moderateScale(8),
  },
  getstart:{
  height: moderateVerticalScale(32),
  color:'#FFFFFF',
  fontFamily: "SF Pro Text",
  fontSize: moderateScale(15),
  fontWeight:moderateScale(50),
  letterSpacing: 0,
  lineWeight: 32,
  textAlign: 'right',
  // marginBottom:moderateScale(52),
  margin:moderateScale(24),
  // marginLeft:moderateScale(23)
}
});
