export { default as Onboarding } from "./ Onboarding/ Onboarding";
export { default as Intially } from "./Intially /Intially";
export { default as Signup } from "./Signup /Signup";
export { default as Login } from "./Login/Login";
export { default as OTPPass } from "./OTPPass/OTPPass";
export { default as Setpass } from "./Setpass/Setpass";
export { default as Location } from "./Location/Location";
export { default as Home } from "./Home/Home";
export { default as PostDetail } from "./PostDetail/PostDetail";
export { default as PostCamera } from "./PostCamera/PostCamera";
export { default as Search } from "./Search/Search";
export { default as EditProfile } from "./EditProfile/EditProfile";
export { default as ChangeProfile } from "./ChangeProfile/ChangeProfile";
export { default as Profile } from "./Profile/Profile";
export { default as Notification } from "./Notification/Notification";
